source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "minima"

group :jekyll_plugins do
  gem "jekyll-feed"
end

platforms :windows do
  gem "tzinfo"
  gem "tzinfo-data"
end

gem "wdm", platforms: [:windows]
